makeERfile <- function (x) {
  for (j in 1:length(x)) {  assign (x[i], getGEO(x[i]))  }

  n <- names (mcf7.gsm.list[i])
  assign (n, makeGSE(x))  
  
  g <- eval(parse(text=n))
  f <- paste(n,".fit",sep='')
  assign (f, summarizeChips(g))

  e <- paste(n,".er",sep='')
  assign (e, getERlevels(eval(parse(text=f)), esr.hgu))
  
  f <- paste("~/Desktop/research/geo-analysis/er-levels/", paste(n,"_er.txt"))
  write.table(eval(parse(text=e)),file,sep='\t',quote=FALSE)
  
  rm(list=x, list=n, x,n,g,f,e)

}

getERlevels <- function (gse.df, probe.lst) {
  # gse.df is a data frame of expression values generated by summarizeChips
  # probe.list is a list of probesets for ESR1 and ESR2 for that chip type

  rn.esr <- NULL
  for (j in 1:length(probe.lst)) { 
    rn.esr<-c(rn.esr,grep(probe.lst[j],row.names(gse.df)))
  }
  #rn.esr is the row numbers of the rows matching the probe.lst 
  
  x <- gse.df[rn.esr,]
  # select only the rows matching the probe.lst

  x <- rbind(x,medn=apply(gse.df,2,median))
  # add a row of the median values of the whole dataframe

  x <- rbind(x,stdv=apply(gse.df,2,sd))
  # add a row of the st dev values of the whole dataframe

  return(x)
}

summarizeChips <- function (gse) {
  chips.norm <- eval(parse(text=gse))
  gsm2cond <- eval(parse(text=paste(gse,".g2c",sep='')))
  design.matrix <- model.matrix(~ -1 + gsm2cond[sampleNames(chips.norm),1])
  colnames(design.matrix) <- levels(gsm2cond[,1])
  rownames(design.matrix) <- rownames(gsm2cond)
  fit <- lmFit(chips.norm,design.matrix)
  fit.df <- as.data.frame.MArrayLM(fit)
  fit.df <- fit.df[,grep("coeff",colnames(fit.df))]
  #   get just the columns with the expression levels ("coefficients")
#write.fit()
  return (fit.df)
}

makeGSE <- function (gsmlist) {
  #makes an ExpressionSet (equivalent to GSE) from series of GSM files

  ids <- Table(eval(parse(text=gsmlist[1])))$ID_REF

  data.matrix <- do.call("cbind",lapply(gsmlist,
    function(x) {
      tab<-Table(eval(parse(text=x)))
      tab$VALUE<-as.numeric(tab$VALUE)
      mymatch<-match(ids,tab$ID_REF)
      return(tab$VALUE[mymatch]) } ))
#function(x) turns the data into a table and reorders the rows by "ids" 
#  (the order of the first gsmfile in the list)
#cbind makes a matrix of all the VALUES in each gsmfile (columns)

  rownames(data.matrix) <- ids
  colnames(data.matrix) <- gsmlist

  pdata <- data.frame(samples=gsmlist)
  rownames(pdata) <- gsmlist
  pheno <- as(pdata, "AnnotatedDataFrame")

  eset <- new("ExpressionSet",exprs=data.matrix,phenoData=pheno)
  return(eset)
}
