getERlevels <- function (gse, probe.lst) {

cat("    Extracting the ER levels for",gse,"\n")

  gse.fit <- eval(parse(text=gse))
  # gse.df is a data frame of expression values generated by summarizeChips
  # probe.list is a list of probesets for ESR1 and ESR2 for that chip type
  
  for (i in 1:length(probe.lst)) {
    p.lst <- probe.lst[[i]]
    p <- names(probe.lst[i])
    rn.esr <- NULL
    for (j in 1:length(p.lst)) { 
      rn.esr<-c(rn.esr,grep(p.lst[j],row.names(gse.fit)))
    }
    #rn.esr is the row numbers of the rows matching the probe.lst 
  
    x <- gse.fit[rn.esr,]
    # select only the rows matching the probe.lst
  
    x <- rbind(x,avg=apply(x,2,mean))
    # add a row of the median values of these rows
  
    x <- rbind(x,stdv=apply(x,2,sd))
    # add a row of the st dev values of these rows
  
  }

  x <- rbind(x,avg.mn=apply(gse.fit,2,mean))
  # add a row of the median values of the whole dataframe

  x <- rbind(x,avg.md=apply(gse.fit,2,median))
  # add a row of the median values of the whole dataframe

  x <- rbind(x,stdv=apply(gse.fit,2,sd))
  # add a row of the st dev values of the whole dataframe

  gse <- strsplit(gse,".",fixed=TRUE)[[1]][1]  #remove .fit from end of name
  colnames(x)<-gsub("coefficients",gse,colnames(x))
  return(x)
}
